### ISSUE TITLE
Make JSON Body Previewer Better

### ISSUE THREAD

**Issue by NghiaTranUIT** [Get-API-App/Issue-Tracker#30]
- Like TablePlus, we should remove the Vertical Line (near the Line Number)
- Make it looks clean

<img width="696" alt="Screenshot 2024-05-28 at 4 43 51 PM" src="https://github.com/Get-API-App/Issue-Tracker/assets/5878421/215b96ab-93e2-43e7-82fb-358911b9965a">

**Comment by huyphams** [comment]
Done!
