### ISSUE TITLE
Missing auth configuration UI

### ISSUE THREAD

**Issue by AlexIsMaking** [Get-API-App/Issue-Tracker#35]
There doesn't seem to be any way to customise the auth settings for requests here?

![CleanShot 2024-05-28 at 12 11 02@2x](https://github.com/Get-API-App/Issue-Tracker/assets/10284831/0a8119db-8c77-4063-b89a-3ce8f61ec9e6)

**Comment by NghiaTranUIT** [comment]
Yes, I'm working on it for the Basic and Bearer.

Do you need specific auth type?

**Comment by AlexIsMaking** [comment]
Great, bearer & basic are all I need thanks.

**Comment by NghiaTranUIT** [comment]
Awesome, I will add it to the next release 👍

**Comment by theskyfloor** [comment]
Need this, excited its coming next!

**Comment by NghiaTranUIT** [comment]
@theskyfloor @AlexIsMaking please try the latest build 1.0.5 (https://github.com/Get-API-App/Issue-Tracker/releases/tag/1.0.5)

- Support Auth: Basic and Bearer Token
- You can import from Postman -> Auto parse and show in the Auth Tab

---------------
Please give a try and share with my your feedback 👍

**Comment by theskyfloor** [comment]
Works perfectly, thanks!
