### ISSUE TITLE
Show/Hide actions for Sidebar and Response pane are not working properly. And the design needs a more improvement.

### ISSUE THREAD

**Issue by usagimaru** [Get-API-App/Issue-Tracker#40]
This issue is a proposal to improve the UI design.

### Sidebar button on the toolbar is not working

I believe that in a typical macOS native app, the sidebar show/hide actions should always be enabled. In the current GetAPI app, the sidebar button on the right side of the toolbar on the main window (or so I think) is not working.

### Split view animations

The toolbar button to show/hide the response pane seems to work, but lacks proper animation.

### NSToolbarItem’s name and tooltip

When I launch toolbar customizing, the AppKit standard toolbar palette appears, but the NSToolbarItem palette name is not properly set.

I also think it would be user friendly to set an appropriate description or name for the Tooltip.

## Issue of the menu bar

In the menu bar, the “View” menu has action to show/hide the sidebar, but lacks action for the Response pane.

If the user hides the toolbar, then there is no way to show/hide the Response pane. I believe that the action should always be available on the menu bar.

## Ideal form

I would be happy to see a more refined design for the toolbar and menu bar, as I believe the general design pattern for macOS apps is to have all the basic actions in the menu bar, with the most frequently used actions in the toolbar as shortcuts.

---

- Get API Version 1.0.4 (4)
- macOS 14.5

**Comment by NghiaTranUIT** [comment]
thanks for your feedback. We definitely refined the Toolbar and Side bar to make it match the standard of macOS.

**Comment by huyphams** [comment]
Done
