### ISSUE TITLE
Should fail instantly if the host can't be found / isn't running

### ISSUE THREAD

**Issue by joshuawright11** [Get-API-App/Issue-Tracker#44]
Made a request to a localhost server that I forgot to start - took a while to timeout. Insomnia fails instantly with a helpful error message

<img width="856" alt="Screenshot 2024-05-28 at 5 56 37 PM" src="https://github.com/Get-API-App/Issue-Tracker/assets/6025554/33c4299e-c5f2-44b9-b3ed-5e299ca74dbb">
<img width="872" alt="Screenshot 2024-05-28 at 5 56 31 PM" src="https://github.com/Get-API-App/Issue-Tracker/assets/6025554/402f6a40-b8f3-4e8b-965c-2f8459479e98">

**Comment by NghiaTranUIT** [comment]
Thanks. Fixing it 👍

**Comment by NghiaTranUIT** [comment]
It's fixed, you can try this Beta build https://download.proxyman.io/beta/GetAPI_1.0.5_Fix_localhost_issue.dmg
