### ISSUE TITLE
Unable to pass Authorization in the format ‘Token …’ for the header

### ISSUE THREAD

**Issue by kavoye** [Get-API-App/Issue-Tracker#51]
The ‘Bearer’ value is hardcoded in the Authorization header, but there are cases where ‘Token …’ needs to be used instead.

![2024-05-30 at 10 49 56@2x](https://github.com/Get-API-App/Issue-Tracker/assets/59966858/53c62891-9099-492f-89cb-e218f36670e1)

**Comment by NghiaTranUIT** [comment]
Then, it's not a Bearer, isn't it?

You can manually edit it by:
1. Select the Auth Tab -> Select: None
2. Back to the Header Tab: Add your Authorization with Token

**Comment by NghiaTranUIT** [comment]
It should like Postman, If you want to have different key, we can support the Custom Auth instead of Bearer

**Comment by kavoye** [comment]
Thank you, it works that way. It’s just a bit confusing because when the Auth Type is selected in the Auth tab, the value in the Headers gets locked, making it seem like it cannot be edited at all.

**Comment by NghiaTranUIT** [comment]
it works like Postman and Paw, since we consider the Auth Tab to be a source of truth. If you want to modify, it's better to modify in the Auth Tab.
