### ISSUE TITLE
[BUG] Deleted requests from root level are not persisted

### ISSUE THREAD

**Issue by gabeins** [Get-API-App/Issue-Tracker#52]
<table>
<tr>
 <th>Get API Version
 <td>1.0.5 (5)
<tr>
 <th>OS Version
 <td>macOS 14.5 (23F79)
</table>

### Description

When deleting a request, if the request is not nested inside a folder, it doesn't persist the deletion. Closing the application and re-opening shows the requests still there.

The issue does not happen if a folder with requests inside gets deleted.

https://github.com/Get-API-App/Issue-Tracker/assets/192261/b72e2a75-8710-4740-aa76-68646c65f9ca

### Expected Behavior

Deleted requests are persisted independently of their folder nesting level.

**Comment by NghiaTranUIT** [comment]
Thanks. We're investigating it. Will fix the in the next release 👍

**Comment by NghiaTranUIT** [comment]
Done
