### ISSUE TITLE
[BUG] echo.getapi.io is slow than httpbin.proxyman.app

### ISSUE THREAD

**Issue by NghiaTranUIT** [Get-API-App/Issue-Tracker#53]
### Description
- Use `httpbin.proxyman.app` usually responses in 100ms

https://github.com/Get-API-App/Issue-Tracker/assets/5878421/30a857ab-ca52-4828-b97b-47d9d4fe15f7

- Meanwhile, `echo.getapi.io` is 300ms

https://github.com/Get-API-App/Issue-Tracker/assets/5878421/c6897034-8222-42f5-bdc6-b8dce2340fc7

**Comment by huyphams** [comment]
N/A
