### ISSUE TITLE
[BUG] Address field keeps text style when pasting

### ISSUE THREAD

**Issue by jrdnp** [Get-API-App/Issue-Tracker#55]
Get API Version | 1.0.6 (6)
-- | --
OS Version |  macOS 14.5 (23F79) 

### Description

When pasting an address copied from Chrome Devtools for example, the main address field keeps text style when pasting

https://github.com/Get-API-App/Issue-Tracker/assets/10980929/261376f9-e233-4a2e-8f44-41f4c04607ae

### Expected Behavior

Text is pasted without style automatically

**Comment by NghiaTranUIT** [comment]
yes, I'm aware of this issue. We're fixing it 👍

**Comment by jrdnp** [comment]
Nice 👌

**Comment by NghiaTranUIT** [comment]
You can workaround by clicking away from the URL Text Field, it will remove the Style

**Comment by NghiaTranUIT** [comment]
It's fixed, you can try this Beta buid at https://download.proxyman.io/beta/GetAPI_1.0.8_Fix_paste_text_style_to_the_URL.dmg
