### ISSUE TITLE
[Feature Request] Support Duplicate Request 😎

### ISSUE THREAD

**Issue by trungpv1601** [Get-API-App/Issue-Tracker#62]
![CleanShot 2024-06-05 at 10 40 49@2x](https://github.com/Get-API-App/Issue-Tracker/assets/25415217/62803eb0-bcbb-43cb-936f-b016ba746ef4)

**Comment by NghiaTranUIT** [comment]
Thanks, we will add it in the next release 👍

**Comment by huyphams** [comment]
Done!
