### ISSUE TITLE
5XX / 4XX coloring feels off

### ISSUE THREAD

**Issue by joshuawright11** [Get-API-App/Issue-Tracker#70]
A 2xx results in a green header, a 4xx results in a red header, and a 5xx results in a green header.

Perhaps a better coloring would be 2xx - green, 4xx - yellow, 5xx - red? (and 1xx / 3xx - white or gray if not already?)

<img width="432" alt="Screenshot 2024-06-12 at 11 16 11 AM" src="https://github.com/Get-API-App/Issue-Tracker/assets/6025554/60b8c9eb-0530-419d-a7db-00b23b831906">
<img width="436" alt="Screenshot 2024-06-12 at 11 16 20 AM" src="https://github.com/Get-API-App/Issue-Tracker/assets/6025554/4eb3f207-e3a5-46a7-804c-ff8f85076c5d">
<img width="437" alt="Screenshot 2024-06-12 at 11 16 04 AM" src="https://github.com/Get-API-App/Issue-Tracker/assets/6025554/02e75fe1-f877-4c15-bddf-bf41bf786a43">

**Comment by NghiaTranUIT** [comment]
It's odd. Let's me fix it 👍

**Comment by NghiaTranUIT** [comment]
It's fixed @joshuawright11 🎉 

Here is the Beta build: https://download.proxyman.io/beta/GetAPI_1.1.0_Fix_status_code_color.dmg

### Changelog
- Fix the 4xx and 5xx color
- Fix the 3xx redirection in the Setting #71 

### Screenshots
<img width="675" alt="Screenshot 2024-06-13 at 9 04 53 AM" src="https://github.com/Get-API-App/Issue-Tracker/assets/5878421/34582150-f7e0-47b0-b830-8cd62cc3cfa6">
