### ISSUE TITLE
Cannot Import Postman Collection

### ISSUE THREAD

**Issue by rrpolanco** [Get-API-App/Issue-Tracker#73]
I tried importing the following Postman collection but it failed:
https://raw.githubusercontent.com/spectrocloud/librarium/version-4-3/docs/api-content/api-docs/v1/api.json

![CleanShot 2024-06-14 at 17 00 53@2x](https://github.com/Get-API-App/Issue-Tracker/assets/6497491/e984a0bb-96c3-4508-a85f-bb2f498b3b35)

**Comment by NghiaTranUIT** [comment]
@rrpolanco are you sure this is a valid Postman collection (https://raw.githubusercontent.com/spectrocloud/librarium/version-4-3/docs/api-content/api-docs/v1/api.json) ?

From what I see, it's not a Postman Collection v2 or v2.1. The structure is completely different.

**Comment by rrpolanco** [comment]
Yup, you're right. That's not a valid postman collection data format. Closing this issue.
