### ISSUE TITLE
Postman collection Imports APIs in Reverse Order

### ISSUE THREAD

**Issue by danteminds** [Get-API-App/Issue-Tracker#77]
When Importing from a Postman Collection, 
all the requests taht are being imported are imported and displayed in reverse order ,
it might be a headache to re-order them when the collection contains subfolders and huge list of requests 

![Get API ](https://github.com/Get-API-App/Issue-Tracker/assets/13228247/31b06d84-33a7-4a17-bdf0-ba0b36360671)

![Postman Collection](https://github.com/Get-API-App/Issue-Tracker/assets/13228247/1ea768f9-e6ec-4e23-9ae3-2478188a1537)

**Comment by NghiaTranUIT** [comment]
Let me investigate it 👍

**Comment by NghiaTranUIT** [comment]
It's fixed @danteminds 👍 
- Beta build: https://download.proxyman.io/beta/GetAPI_1.1.1_Fix_import_postman_with_wrong_orders.dmg
