### ISSUE TITLE
[Feature Request] Press return in folder view to rename request / folder

### ISSUE THREAD

**Issue by Trashpants** [Get-API-App/Issue-Tracker#81]
I'm used to this functionality in VSCode and other apps, rather than having to right click > rename request would be nice to have it here to keep things organised easier

**Comment by NghiaTranUIT** [comment]
Thanks, let me add it 👍

**Comment by NghiaTranUIT** [comment]
@Trashpants you can try this Beta build: https://download.proxyman.io/beta/GetAPI_1.1.1_Rename_by_enter.dmg
- Enter / Return to rename the current selection


https://github.com/Get-API-App/Issue-Tracker/assets/5878421/7e84bef5-425a-4050-b9a2-4398c5068d05

**Comment by Trashpants** [comment]
Hey works as expected although I do get an audible system notification when you press enter - can that be removed?
